### ISSUE TITLE
get all nodes latest block number and time

### ISSUE THREAD

**Issue by gsj5** [zsluedem/transaction-server#1]
To ensure network is working as expected, it would be helpful to have an API which provides all nodes latest block number and when the block was added to the node.  Perhaps https://status.rchain.coop/api/validators can be extended to provide this additional information?

**Comment by zsluedem** [comment]
https://github.com/zsluedem/transaction-server/commit/7bd887cc564e4c961d8d66915ee68251b83aacab
done
